// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hirhub-crema/CremaAntracite.tsx": () => import("../components/mockups/hirhub-crema/CremaAntracite.tsx"),
  "./components/mockups/hirhub-pergamena/PergamenaScura.tsx": () => import("../components/mockups/hirhub-pergamena/PergamenaScura.tsx")
};
